# Generated by Django 2.2.4 on 2019-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0002_profile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(related_name='profiles', to='posts.Tag'),
        ),
    ]
