# Generated by Django 2.2.6 on 2020-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_hoursofop_hoursopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursopen',
            name='weekday',
            field=models.CharField(max_length=10),
        ),
    ]
